### ISSUE TITLE
Allow input of different type of files (e.g. Jpeg,tiff...)

### ISSUE THREAD

**Issue by fritz-hh** [fritz-hh/OCRmyPDF#17] opened 2013-04-26 18:36 UTC

**Comment by zorglups** [comment] 2015-03-10 21:28
I'm working on this and will share my work with you.

**Comment by fritz-hh** [comment] 2015-03-10 21:30
Great!

**Comment by jbarlow83** [comment] 2015-03-29 21:57
duplicate of issue #104

**Closed by jbarlow83** 2015-03-29 21:57 UTC
Labels: enhancement
