### ISSUE TITLE
Raw image to OCRmyPDF

### ISSUE THREAD

**Issue by geaplanet** [fritz-hh/OCRmyPDF#104] opened 2015-03-08 10:46 UTC
Is there any posibility to use OCRmyPDF passing raw TIFF images as a parameter?
OCRmyPDF convert pdfs to image to work with them, but in case you have got raw images from scanner or cam, how can you use it?

**Comment by zorglups** [comment] 2015-03-10 21:32
My scanner produces multi jpg per document and I'm adapting the script to deal with multiple image files to create the final pdf.
When get something working, I'll post a comment here.

**Comment by fritz-hh** [comment] 2015-03-10 21:35
Hi. Currently you need to convert the images to PDF first (e.g. using ghostscript, imagemagik). 
Note: A ticket for this enhancement already exists (#17), but it is still open

**Comment by geaplanet** [comment] 2015-03-14 09:02
Convert images to PDF first is not an option because I have books in TIFF format and the total size is about 5Gb!

**Comment by zorglups** [comment] 2015-03-29 21:10
@geoplanet

I have a need for this too. We are first translating OCRmyPDF.sh into Python and I will then add support to ingest images (may be multiple ordered images) instead of pdf.

**Comment by zorglups** [comment] 2015-03-29 21:18
IMHO this is a duplicate of #17 and could therefore be closed.

**Comment by geaplanet** [comment] 2015-04-12 10:54
I get this when I try to use the script:

---------------------------------------------------------
./OCRmyPDF.sh -v -l spa 010.tif 010.pdf
When using programs that use GNU Parallel to process data for publication please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; and it won't cost you a cent.
Or you can get GNU Parallel without this requirement by paying 10000 EUR.

To silence this citation notice run 'parallel --bibtex' once or use '--no-notice'.

Page 0001: Expecting exactly 1 image covering the whole page (found 0). Cannot compute dpi value.
Page 0001: Continuing anyway, assuming a default resolution of 300 dpi
Could not extract page 0001 as ppm from "/tmp/pruebas/010.tif". Exiting...
Error: May not be a PDF file (continuing anyway)
Error: PDF file is damaged - attempting to reconstruct xref table...
Error: Couldn't find trailer dictionary
Error: Couldn't read xref table
Error: May not be a PDF file (continuing anyway)
Error: PDF file is damaged - attempting to reconstruct xref table...
Error: Couldn't find trailer dictionary
Error: Couldn't read xref table
Error: May not be a PDF file (continuing anyway)
Error: PDF file is damaged - attempting to reconstruct xref table...
Error: Couldn't find trailer dictionary
Error: Couldn't read xref table
parallel: Starting no more jobs. Waiting for 1 jobs to finish. This job failed:
./src/ocrPage.sh /tmp/pruebas/010.tif 0001\ 6373\ 7999 0001 /tmp/tmp.PLXzCNYRF2 1 spa 0 0 0 0 0 0 0 0 
----------------------------------------------

Is it possible pass as argument a bulk of files? I tryed *.tif, but it doesn't work.
I have tested with jpg and tif files.

**Comment by jbarlow83** [comment] 2015-04-12 21:09
The input has to be a PDF. Conversion of raw images is a frequently requested feature.

You can use tiff2pdf (from poppler-utils or xpdf) or the Python package img2pdf to do batch command line conversion of images to PDF.

**Closed** 2015-12-05 22:40 UTC
