### ISSUE TITLE
Create a Python front-end for OCRmyPDF.sh

### ISSUE THREAD

**Issue by jbarlow83** [fritz-hh/OCRmyPDF#65] opened 2014-02-03 04:44 UTC
I'd like to propose moving part of OCRmyPDF.sh to a Python script with an argparse command line parser (like hocrTransform.py).

Python's argparse is great at taking care of the messy and boring details of providing usage information and validating parameters. It also a clean, portable way to get long and short options (```--deskew``` and ```-d```) which will be helpful as more options come available. This Python script could generate the environment variables and pass them to OCRmyPDF.sh.

Also, I'd suggest naming it ```ocrmypdf``` without any extension. In another issue someone mentioned packaging and dependency resolution – this would be great, package managers will want to see a lowercase executable script as the entry point.

**Comment by zorglups** [comment] 2015-03-29 21:19
I think this could be closed as duplicate of #94

**Closed** 2015-03-29 21:56 UTC
Labels: enhancement
